name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Install Dependencies
    - name: Install Dependencies
      run: npm install
      working-directory: WEBPage/Frontend

    # Build
    - name: Build
      run: npm run build -- --output-path=dist
      working-directory: WEBPage/Frontend

    # Deploy
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages  # Der Branch, auf den deployt wird
        folder: WEBPage/Frontend/dist  # Der Ordner, der deployt wird
